csv_summarizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('summarizer.urls', namespace='summarizer')),
    path('auth/', include('authentication.urls', namespace='authentication'))
]

summarizer/urls.py
from django.urls import path
from .views import HomeView, UploadCSVView
# SummarizeCSVView, SuccessUploadView


app_name = 'summarizer'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('upload_file/', UploadCSVView.as_view(), name='upload_file'),
    # path('success_upload', SuccessUploadView.as_view(), name='success_upload'),
    # path('summarize/', SummarizeCSVView.as_view(), name='summarize')
]

base_config/models.py
from django.db import models

# Create your models here.

base_config/views.py
from django.shortcuts import render

# Create your views here.

base_config/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <a class="navbar-brand" href="{% url 'summarizer:home'%}">CSV Summarizer</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'summarizer:upload_file' %}">Summarize CSV</a>
        <a class="nav-item nav-link" href="#">View Results</a>
      </div>
    </div>
  </nav>